84 Institutions management
buerokratt/CentOps pull request #121
Opened 2023-06-19 09:41 UTC by baha-a

2023-06-20 10:32 UTC, 1AhmedYasser approved these changes

2023-06-26 18:07 UTC, turnerrainer requested changes
Using `UPDATE` and `DELETE` are forbidden, every action has to result as a new entry in the db table.

2023-06-27 05:28 UTC, baha-a commented
> Using `UPDATE` and `DELETE` are forbidden, every action has to result as a new entry in the db table.

Okay, I will change it.

2023-06-28 11:35 UTC, baha-a commented
> > Using `UPDATE` and `DELETE` are forbidden, every action has to result as a new entry in the db table.
> 
> Okay, I will change it.

Done

2023-06-29 12:51 UTC, PaulaMerle approved these changes

2023-06-29 12:58 UTC, merged