13 Technical setup
buerokratt/CentOps pull request #20
Opened 2023-05-15 23:10 UTC by baha-a

2023-05-17 11:09 UTC, karljogi requested changes

2023-05-17 11:09 UTC, karljogi commented on DSL/DMapper/hbs/dummy.handlebars
> +]
Please add a newline at the end of the file

2023-05-17 11:29 UTC, baha-a commented on DSL/DMapper/hbs/dummy.handlebars
> +]
Added.

2023-05-17 11:38 UTC, karljogi approved these changes

2023-05-22 12:05 UTC, turnerrainer approved these changes
Approve as an initial commit

2023-05-22 12:05 UTC, merged