22 Create unique invitation ID for application
buerokratt/CentOps pull request #21
Opened 2023-05-17 16:05 UTC by karljogi

Issue #22 

~~NB! Contains changes from #46, merge it before current PR.~~

Currently missing implementation for #19.

Created separate directories for public and private ruuter. Added api-documentation.yml file where all future endpoints should be documented.

2023-05-22 23:41 UTC, baha-a requested changes

2023-05-22 23:41 UTC, baha-a commented on GUI/src/pages/CreateInvitationPage.tsx
> +        ></FormInput>
Please use self closed tags in case of no nested elements.

2023-05-22 23:41 UTC, baha-a commented on DSL/Ruuter/POST/create-invitation.yml
> +  next: create_invitation
Note: providing `next` statement is optional, for example here if you removed or kept this line the execution will be the same.

2023-05-22 23:41 UTC, baha-a commented on DSL/Ruuter/POST/create-invitation.yml
> +  next: get_invitation_code
#### Similar to previous comment:

Note: providing `next` statement is optional, for example here if you removed or kept this line the execution will be the same.

2023-05-22 23:41 UTC, baha-a commented on DSL/Ruuter/POST/create-invitation.yml
> +  next: return_ok
#### Similar to previous comment:

Note: providing `next` statement is optional, for example here if you removed or kept this line the execution will be the same.

2023-05-23 06:56 UTC, baha-a approved these changes

2023-05-26 09:51 UTC, turnerrainer approved these changes

2023-05-26 10:13 UTC, baha-a requested changes

2023-05-26 10:13 UTC, baha-a commented on GUI/src/pages/CreateInvitationPage.tsx
> +  const [email, setEmail] = useState<string>('');
Please remove `<string>` if not needed to make it consistent with other `useState` statements.

2023-05-31 12:37 UTC, baha-a approved these changes

2023-05-31 12:38 UTC, turnerrainer approved these changes
Approved as initial commit

2023-05-31 12:38 UTC, merged